### ISSUE TITLE
[Bug] taken course 데이터가 불러와지지 않는 오류

### ISSUE THREAD

**Issue by sleeep23** [Gijol/gijol-backend#76]
**Describe the bug**
`/api/v1/users/me/taken-courses` 라우트로 요청을 보낼 시, `{"message":"해당하는 학점이 없습니다."}` 로 400 에러가 납니다.

**To Reproduce**
1. 회원가입시 자기 성적 파일 업로드하기 (여기서 정상적인 업로드가 안되었다는 오류가 났습니다.)
2. 이후 마이페이지를 통해 다시 다른 파일을 업로드 하기 (여기선 정상적으로 업로드 되었습니다.)
3. 하지만 위 두 경우에서, 내 정보를 확인할 때, 해당하는 학점이 없다는 에러가 납니다.

**Expected behavior**
- 정상적으로 업로드 되어야 합니다.
- 업로드 이후 수정된 데이터가 정상적으로 보여야 합니다.

**Screenshots**
<img width="1440" alt="스크린샷 2023-07-31 오후 8 44 10" src="https://github.com/Gijol/gijol-backend/assets/88386139/03d75322-951c-4ee9-b34b-3cab9237784e">

**Additional context**

**Comment by ChoiEungi** [comment]
퇴근하고 확인해볼게요~
